### ISSUE TITLE
"go get" hangs

### ISSUE THREAD

**Issue by ymettier** [fatih/pool#8]
Hello,

I try to compile InfluxDB and I have a problem with pool.v2.

```
$ rm -rf src/gopkg.in/fatih/
$ go get -v gopkg.in/fatih/pool.v2
Fetching https://gopkg.in/fatih/pool.v2?go-get=1
Parsing meta tags from https://gopkg.in/fatih/pool.v2?go-get=1 (status code 200)
get "gopkg.in/fatih/pool.v2": found meta tag main.metaImport{Prefix:"gopkg.in/fatih/pool.v2", VCS:"git", RepoRoot:"https://gopkg.in/fatih/pool.v2"} at https://gopkg.in/fatih/pool.v2?go-get=1
```

The comand `go get ...` hangs. 

```
$ ps -ef|grep git
[...] git clone https://gopkg.in/fatih/pool.v2 /home/yves/GO_Projects/src/gopkg.in/fatih/pool.v2
[...] git-remote-https https://gopkg.in/fatih/pool.v2 https://gopkg.in/fatih/pool.v2
[...] git fetch-pack --stateless-rpc --lock-pack --thin --no-progress https://gopkg.in/fatih/pool.v2  efs/heads/master  efs/heads/v1.0.0  efs/heads/v2.0.0
```

OK, Ask google... Suggestion :
```
$ rm -rf src/gopkg.in/fatih/
$ git clone --branch v2 https://github.com/fatih/pool.git $GOPATH/src/gopkg.in/fatih/pool.v2
```
This works.

And compilation of InfluxDB fails.
```
$ cd $GOPATH/src/github.com/influxdb
$ go build  ./...
# github.com/influxdb/influxdb/cluster
influxdb/cluster/shard_writer.go:44: undefined: pool.PoolConn
```

But I had noticed something in fatih/pool : 
```
$ cd $GOPATH/src/src/gopkg.in/fatih/pool.v2
$ git branch
* master
  v2.0.0
```

Maybe if I were working with branch v2.0.0 it would work better ?
I'm a beginner with GO so I don't know how to ask go to use branch v2.0.0. I have a better knowledge of git. I merge v2.0.0 into master : 
```
$ cd $GOPATH/src/src/gopkg.in/fatih/pool.v2
$ git merge v2.0.0
$ cd $GOPATH/src/github.com/influxdb
$ go build  ./...
```

Now InfluxDB compiles successfully.

What have I missed ?
What's the problem with gopkg.in (I have no problem with github.com and golang.com)

I'm using go1.5 (installed with gvm) and git-1.7.1 (from redhat rpms) on a standard Redhat 6.6.

**Comment by adithyabenny** [comment]
+1

**Comment by fatih** [comment]
Sometimes gopkg behaves wrong (due network issues). It's not happening always. Thanks!
